# Generated by Django 6.0.1 on 2026-01-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_message',
            field=models.TextField(blank=True, help_text='Message to the applicant from the secretariat'),
        ),
    ]
