# Generated by Django 6.0.1 on 2026-01-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_admin_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='admin_message',
            field=models.TextField(blank=True, default='', help_text='Message to the applicant from the secretariat'),
        ),
    ]
